channels:
  channel1:
    enabled: true
    input: rist://104.200.103.171:4600
    last_error: null
    metrics_port: 9201
    name: bbcw
    output: udp://224.100.200.1:5000
    process_id: null
    settings:
      buffer: 500
      encryption_type: null
      profile: 1
      secret: null
      virt_src_port: 4601
    status: stopped
  channel2:
    enabled: true
    input: rist://104.200.103.171:4602
    last_error: null
    metrics_port: 9202
    name: cnnus
    output: udp://224.100.200.1:5001
    process_id: null
    settings:
      buffer: 1000
      encryption_type: null
      profile: 1
      secret: null
      virt_src_port: 4603
    status: stopped
  channel3:
    enabled: true
    input: rist://104.200.103.171:4604
    last_error: null
    metrics_port: 9203
    name: CBCTV8
    output: udp://224.100.200.1:5002
    process_id: null
    settings:
      buffer: 500
      encryption_type: null
      profile: 1
      secret: null
      virt_src_port: 4605
    status: stopped
  channel4:
    enabled: true
    input: rist://104.200.103.171:4606
    last_error: null
    metrics_port: 9204
    name: bet
    output: udp://224.100.200.1:5003
    process_id: null
    settings:
      buffer: 500
      encryption_type: null
      profile: 1
      secret: null
      virt_src_port: 4607
    status: stopped
